name: qlib
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - gcc=12.1.0=h9ea6d83_10
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libsanitizer=12.1.0=ha89aaad_17
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hc23ea64_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiohttp-jinja2==1.6
      - aiosignal==1.4.0
      - alembic==1.17.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - authlib==1.6.5
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - catboost==1.2.8
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - choreographer==1.1.2
      - clarabel==0.11.1
      - click==8.3.0
      - cloudpickle==3.1.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cvxpy==1.7.3
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.68.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.119.0
      - fastjsonschema==2.21.2
      - fastmcp==2.12.5
      - filelock==3.20.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphviz==0.21
      - greenlet==3.2.4
      - gunicorn==23.0.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kaleido==1.1.0
      - kiwisolver==1.4.9
      - lark==1.3.0
      - lazy-object-proxy==1.12.0
      - lightgbm==4.6.0
      - linkify-it-py==2.0.3
      - logistro==2.0.0
      - loguru==0.7.3
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mcp==1.16.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mlflow==3.5.0
      - mlflow-skinny==3.5.0
      - mlflow-tracing==3.5.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - narwhals==2.8.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.3.4
      - nvidia-nccl-cu12==2.28.3
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.3
      - osqp==1.0.5
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parse==1.20.2
      - parso==0.8.5
      - pathable==0.4.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - prettytable==3.16.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyinquirer==1.0.3
      - pymongo==4.15.3
      - pypandoc==1.16.2
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyqlib==0.9.8.dev17+g09cbc8c16
      - pytest==8.4.2
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - python-redis-lock==4.0.0
      - pytorch-triton-rocm==3.2.0+rocm6.4.2.git7e948ebf
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - questionary==2.1.1
      - redis==6.4.0
      - referencing==0.36.2
      - regex==2025.10.23
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-rst==1.3.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - scs==3.2.9
      - send2trash==1.8.3
      - setuptools-scm==9.2.2
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.1.0
      - terminado==0.18.1
      - textual==6.4.0
      - textual-dev==1.8.0
      - textual-serve==1.1.2
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.6.0+rocm6.4.2.git76481f7c
      - torchaudio==2.6.0+rocm6.4.2.gitd8831425
      - torchvision==0.21.0+rocm6.4.2.git4040d51f
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.1
      - widgetsnbextension==4.0.14
      - xgboost==3.1.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/ash/miniconda3/envs/qlib
