qlib_path = "/home/ash/quant/qlib"

qlib_yaml = [
    "/examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml",
    "/examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha360.yaml",
]