qlib_path = "/home/ash/quant/qlib"

qlib_yamls = [
    "examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml",
    "examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha360.yaml",
]

output_path = "~/.qlibAssistant/"