# 该文件可被命令行输入覆盖

# 实验相关配置
# exp_name: test1222pm
# task_list:
#   - my_taskA
#   - my_taskB
#   - my_taskC
uri_folder: "~/.qlibAssistant/mlruns"

pfx_name: p
sfx_name: s

model_name: Linear
dataset_name: Alpha158
stock_pool: csi300
step: 40

# rolling_type:sliding
rolling_type: expanding

# 限定股票列表
stock_list:
  - SH601699
  # - SH601318
  # - my_test_stockA

# 预测日期区间, 替代 test segment
predict_dates:
  - start: 2025-12-19
    end: 2025-12-19

# 模型过滤器, 支持正则表达式
model_filter:
  # - "158"
  # - testxx
  - p_LinearModel_Alpha158_s_20260102_19