# 该文件可被命令行输入覆盖

# 实验相关配置
# exp_name: test1222pm
# task_list:
#   - my_taskA
#   - my_taskB
#   - my_taskC
uri_folder: "~/.qlibAssistant/mlruns"
anilysis_folder: "~/.qlibAssistant/anilysis"

pfx_name: p
sfx_name: s

model_name: Linear
dataset_name: Alpha360
stock_pool: csi300
step: 40

# rolling_type:sliding
rolling_type: expanding

# 限定股票列表
stock_list:
  - SH601699
  - SH601318
  # - my_test_stockA

# 预测日期区间, 替代 test segment
predict_dates:
  - start: 2026-01-22
    end: 2026-01-25

# 模型过滤器, 支持正则表达式
model_filter:
  - Alpha158.*csi300

rec_filter:
  - ic: 0.1
  - icir: 0.6
  - rankic: 0.05
  - rankicir: 0.02