# 该文件可被命令行输入覆盖

# 实验相关配置
exp_name: test1222pm
step: 400
task_list:
  - my_taskA
  - my_taskB
  - my_taskC

# 限定股票列表
stock_list:
  - SH601699
  - SH601318
  # - my_test_stockA

# 预测日期区间, 替代 test segment
predict_dates:
  - start: 2025-12-20
    end: 2025-12-24

# 模型过滤器, 支持正则表达式
model_filter:
  - "158"
  # - testxx
  # - pm